import streamlit as st
from sqlalchemy import text


# =========================================================
# Connection
# =========================================================

def get_connection():
    """
    Return the Streamlit PostgreSQL connection.

    Connection details are loaded automatically from:
    .streamlit/secrets.toml
    """
    return st.connection(
        "postgresql",
        type="sql"
    )


# =========================================================
# Database initialization
# =========================================================

def init_database() -> None:
    """
    Create the tables needed for the experiment.
    Existing tables are left untouched.
    """

    connection = get_connection()

    create_participants = """
        CREATE TABLE IF NOT EXISTS participants (
            participant_id TEXT PRIMARY KEY,

            condition TEXT
                CHECK (
                    condition IS NULL
                    OR condition IN ('baseline', 'openness')
                ),

            started_at TIMESTAMPTZ NOT NULL
                DEFAULT CURRENT_TIMESTAMP,

            completed_at TIMESTAMPTZ
        );
    """

    create_messages = """
        CREATE TABLE IF NOT EXISTS messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            participant_id TEXT NOT NULL
                REFERENCES participants(participant_id)
                ON DELETE CASCADE,

            question_nr INTEGER NOT NULL
                CHECK (question_nr > 0),

            message_nr INTEGER NOT NULL
                CHECK (message_nr > 0),

            role TEXT NOT NULL
                CHECK (role IN ('user', 'assistant')),

            content TEXT NOT NULL,

            created_at TIMESTAMPTZ NOT NULL
                DEFAULT CURRENT_TIMESTAMP,

            UNIQUE (
                participant_id,
                question_nr,
                message_nr,
                role
            )
        );
    """

    create_submissions = """
        CREATE TABLE IF NOT EXISTS submissions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            participant_id TEXT NOT NULL
                REFERENCES participants(participant_id)
                ON DELETE CASCADE,

            question_nr INTEGER NOT NULL
                CHECK (question_nr > 0),

            response_type TEXT NOT NULL
                CHECK (response_type IN ('initial', 'final')),

            content TEXT NOT NULL,

            created_at TIMESTAMPTZ NOT NULL
                DEFAULT CURRENT_TIMESTAMP,

            updated_at TIMESTAMPTZ NOT NULL
                DEFAULT CURRENT_TIMESTAMP,

            UNIQUE (
                participant_id,
                question_nr,
                response_type
            )
        );
    """

    with connection.session as session:
        session.execute(text(create_participants))
        session.execute(text(create_messages))
        session.execute(text(create_submissions))
        session.commit()


# =========================================================
# Participants
# =========================================================

def register_participant(
    participant_id: str,
    condition: str | None = None
) -> None:

    if condition not in {None, "baseline", "openness"}:
        raise ValueError("Invalid experimental condition.")

    connection = get_connection()

    query = text("""
        INSERT INTO participants (
            participant_id,
            condition
        )
        VALUES (
            :participant_id,
            :condition
        )
        ON CONFLICT (participant_id)
        DO NOTHING;
    """)

    with connection.session as session:
        session.execute(
            query,
            {
                "participant_id": participant_id,
                "condition": condition
            }
        )
        session.commit()


def set_participant_condition(
    participant_id: str,
    condition: str
) -> None:

    if condition not in {"baseline", "openness"}:
        raise ValueError("Invalid experimental condition.")

    connection = get_connection()

    query = text("""
        UPDATE participants
        SET condition = :condition
        WHERE participant_id = :participant_id;
    """)

    with connection.session as session:
        session.execute(
            query,
            {
                "participant_id": participant_id,
                "condition": condition
            }
        )
        session.commit()


def mark_participant_completed(
    participant_id: str
) -> None:

    connection = get_connection()

    query = text("""
        UPDATE participants
        SET completed_at = CURRENT_TIMESTAMP
        WHERE participant_id = :participant_id;
    """)

    with connection.session as session:
        session.execute(
            query,
            {
                "participant_id": participant_id
            }
        )
        session.commit()


# =========================================================
# LLM messages
# =========================================================

def save_llm_message(
    participant_id: str,
    question_nr: int,
    message_nr: int,
    role: str,
    content: str
) -> None:

    if role not in {"user", "assistant"}:
        raise ValueError(
            "Role must be 'user' or 'assistant'."
        )

    connection = get_connection()

    query = text("""
        INSERT INTO messages (
            participant_id,
            question_nr,
            message_nr,
            role,
            content
        )
        VALUES (
            :participant_id,
            :question_nr,
            :message_nr,
            :role,
            :content
        )
        ON CONFLICT (
            participant_id,
            question_nr,
            message_nr,
            role
        )
        DO UPDATE SET
            content = EXCLUDED.content;
    """)

    with connection.session as session:
        session.execute(
            query,
            {
                "participant_id": participant_id,
                "question_nr": question_nr,
                "message_nr": message_nr,
                "role": role,
                "content": content
            }
        )
        session.commit()


# =========================================================
# Participant submissions
# =========================================================

def save_submission(
    participant_id: str,
    question_nr: int,
    response_type: str,
    content: str
) -> None:

    if response_type not in {"initial", "final"}:
        raise ValueError(
            "Invalid response type."
        )

    connection = get_connection()

    query = text("""
        INSERT INTO submissions (
            participant_id,
            question_nr,
            response_type,
            content
        )
        VALUES (
            :participant_id,
            :question_nr,
            :response_type,
            :content
        )
        ON CONFLICT (
            participant_id,
            question_nr,
            response_type
        )
        DO UPDATE SET
            content = EXCLUDED.content,
            updated_at = CURRENT_TIMESTAMP;
    """)

    with connection.session as session:
        session.execute(
            query,
            {
                "participant_id": participant_id,
                "question_nr": question_nr,
                "response_type": response_type,
                "content": content
            }
        )
        session.commit()
