SCIENCE_LLM_API_KEY = "sk-9844d1bee7004019a6709b908bef59cb"

[connections.postgresql]
url = "postgresql+psycopg://neondb_owner:npg_Y3PhCkN1zspm@ep-flat-sun-b2rs2waw-pooler.c-6.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
