SCIENCE_LLM_API_KEY = "sk-bfc2214fec3246c88b3ed57ea7f94606"

[connections.postgresql]
url = "postgresql://neondb_owner:npg_xsXjHNAb21Vo@ep-flat-sun-b2rs2waw-pooler.c-6.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
